### ISSUE TITLE
How to log to an other mediawiki  ?

### ISSUE THREAD

**Issue by mezianeAITE** [Gelbpunkt/aiowiki#11]
Hi,
I'm using mediawiki to deploy wiki with my specific configuration. I would like to use your lib to upload, edit the page. But i search and i can't find how to connect to an other wiki than mediawiki.
Is it possible ? How ?
Something like: wiki.login("http://mywiki/api.php", "test", "pass1234")
Best regards

**Comment by Gelbpunkt** [comment]
```py
wiki = aiowiki.Wiki("https://mywiki/api.php")
await wiki.login("test", "pass1243")
page = wiki.get_page("My page title")
await page.edit("New content goes here")
```
This should work just fine.

**Comment by mezianeAITE** [comment]
perfect, it works.
Thank you so much.

**Comment by Gelbpunkt** [comment]
Nice to hear that!
